auto: true

markdown: kramdown

highlighter: 'rouge'
#paginate: 8
permalink: /:title

name: “Lijun Yu's Blog”
title: Lijun Yu's blog
description: Everything about Lijun Yu.
url: http://helloourworld.github.io
feed: /atom.xml
author_info: <a href="http://helloourworld.github.io/">Welcome</a>
